### ISSUE TITLE
Reach out regarding ESA talk last year?

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#14]
See notes from Caitlin.

**Comment by cmacmac** [comment]
Sent an email to Rob Nowicki.

**Comment by cmacmac** [comment]
I talked with Rob on the phone on Monday, his paper is still in review, but I think it's worth adding a 'personal communication' placeholder. I can add a sentence with this to the intro or discussion.

**Comment by seananderson** [comment]
Let's hold off on this until we have something more than a personal communication. There's this cool paper I read that 'personal communication' is rarely used now. ;)
