### ISSUE TITLE
Decide which terms should be in italics

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#16]
> Which terms to put in italics is something that I've struggled with. My thinking was that the italic terms specifically referred to complete n-grams that can be seen on a figure panel when that figure panel is being referred to. If the terms are used in some other context then they aren't in italics. In other cases, like theory of island biogeography, only the first three words are part of the n-gram since we didn't analyze the 4-grams. I could be convinced to be more liberal with the italics though.

**Comment by SKuebbing** [comment]
I like this approach and think it makes sense. I suggest leaving as is.
