### ISSUE TITLE
Incorporate something about the "field is getting wider"

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#20]
"there are so many more papers published in more journals today and so there's more space for different kinds of ecologists"

Also see: https://dynamicecology.wordpress.com/2019/05/01/quantifying-the-life-histories-of-ecological-ideas/

Likely cite E O Wilson's book as part of this thought?

**Comment by cmacmac** [comment]
The Dynamic Ecology blog has covered this really well, and with thorough historical context. Can we cite a blog? Are there papers that contain the same discussion?
https://dynamicecology.wordpress.com/2013/06/10/and-the-most-cited-ecology-papers-from-the-70s-80s-and-90s-are/

**Comment by seananderson** [comment]
There is something about this in the last sentence of the abstract and in the last paragraph of the discussion now.
