### ISSUE TITLE
Does the relative weight (space) allocated to the various topics make sense?

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#25]
- Conservation and applied ecology gets a lot of space in the writing. There's lots of interesting content there, but I just want to make sure we aren't disproportionately emphasizing some topics over others.

- Perhaps there is one or two more observations that can be made about the genetics panels?

- Ecological scale in community ecology is only getting one (long) paragraph but this seems like the meat of ecology. Is there enough emphasis here? Maybe this is OK because so much of the top terms and fill in the blanks sections also emphasize more general ecology?

**Comment by meredithholgerson** [comment]
I can work on the ecological scale question-- can someone else handle genetics and / or proportion of other topics?

**Comment by meredithholgerson** [comment]
Why is the ecological scale section focused on community ecology (e.g., Figure 3c-f versus population or ecosystem)?  It seems cherry picked, especially as "population ecology" is second to species in the scale figure (Fig. 3a and b)?

**Comment by meredithholgerson** [comment]
How much space do we have for submission?  I think genetics and scale could be added to, and maybe conservation / applied ecology could be condensed.

**Comment by seananderson** [comment]
I think Figure 3 grew organically into what it is. That's a good point about population ecology. What do you think we would include? Intrinsic growth rate? carrying capacity? r-selection, k-selection (I think we had tried this at one point; probably has a high false positive issue)?

Our idea with the handpicked panels was to illustrate some interesting features, not to be totally unbiased or comprehensive, so I could be convinced to leave it as is.

I think we already have a fair bit of data in the figures for genetics, although I agree we could probably include more text. I agree that we could probably shorten conservation and applied ecology a bit, although it's always hard to do.

There isn't a hard limit on space with nature ecology and evolution. Figure wise, I imagine we are already pushing it though.
