### ISSUE TITLE
Check the voice across the results section paragraphs

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#26]
These were drafted by different authors. I've done my best to edit them into a consistent voice (including consistent word use and consistent tense) but there might be inconsistencies remaining.

**Comment by meredithholgerson** [comment]
I think the voice sounds consistent, but many sentences use the passive voice.  I prefer active voice, but don't want to edit the whole paper if everyone else is happy with passive voice (I think it's just personal preference / training).

**Comment by seananderson** [comment]
I'm all for the active voice everywhere except for those very few times
when you really do need to be ambiguous about the subject.

>
