### ISSUE TITLE
Make sure all the supplementary figures and tables are referenced in the text

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#27]
And in the right order.

**Comment by SKuebbing** [comment]
Hey Sean,

Once you pull in the decadal figures in the new version I can finish this. Right now everything looks in order. But, it might be easier for me if you sent me a PDF version of the text (or let me know how I can make my own?).
Thanks! sara

**Comment by SKuebbing** [comment]
Sean - created a new branch with ONLY minor changes to fig references.  See comments in the Commit section (briefly: 1)need to switch #s on S2 and S3, 2)current S2 panels c-d not references in text (suggested text within to reference, or remove, these are niche panels, 3) decadal giant figs S9-S16 not referenced, I added some suggested text to reference them. you just need to decide if that text should go in Results or Methods.  Depending on where they go, we may need to renumber supp figures.

**Comment by seananderson** [comment]
Thanks. I've rearranged the figures now in the supplement. I think we should reference the decadal-giant figures early in the results... probably at the same time as introducing the first main figure.
