### ISSUE TITLE
Are there any missing references that could enhance the paper?

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#28]

**Comment by SKuebbing** [comment]
See reworked text and cites.  Many included, we may not have space for them all...

**Comment by seananderson** [comment]
Thanks. Could you make sure to send me the reference data? See this thread on the pull request: https://github.com/seananderson/ecology-trends/pull/39

Even if you just paste the basic metadata (authors, titles, year) here, I can look them up. If you already have them in a reference manager than you could export them in BibTeX format and paste that here.
