### ISSUE TITLE
Consider restructuring the first paragraph of the discussion

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#29]
This is one of the most important paragraphs of the paper. I tend to use this paragraph in papers as a summary of the main results. It's pretty good as is but given its importance could use some extra focus about the main message we want to drive home.

This might be a place to emphasize the wider breadth of ecology today. Something about how there is space for many more types of ecologists now.

**Comment by SKuebbing** [comment]
I can take this on... but I'd like to see if you like the flavor of the suggested changes to the Introduction before tacking the Discussion.

**Comment by SKuebbing** [comment]
Ok, see pull request on this.  Suggested changes in there; i'm not wedded to them.
