### ISSUE TITLE
Incorporate Diogo and Mallika's comments

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#32]
See the PDF.

**Comment by cmacmac** [comment]
Mallika wrote that "reflecting on what has been accomplished, deconstructing colonial language/implicit bias in the field?" should be included the reasons for analyzing/reviewing the lexicon of the published literature (Intro). I think this should be incorporating, but not sure how to state it simply without glossing over all of JEDI and the problematic and exclusive history of ecology.

**Comment by cmacmac** [comment]
I just had a thought — I saw on twitter last month that Rae Wynn Grant is writing an invited response to[ this fairly terrible Science piece](https://www.sciencemag.org/news/2019/04/historians-expose-early-scientists-debt-slave-trade). I think it might be a great citation for the colonial past of ecology.
