### ISSUE TITLE
Include full journal inclusion/exclusion table in supplement

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#34]
This comes from a comment from @meredithholgerson.

My thoughts:

I dug into this and it looks like it was excluded as part of our painful group decisions here: 
https://github.com/seananderson/ecology-trends/blob/master/data/journal-filtering.csv

there is a key here:
https://github.com/seananderson/ecology-trends/blob/master/data/inclusion-criteria.csv

My guess is we were thinking that it would include a lot of papers on the abiotic side of things. We could revisit that though and if we do that then we should give all the other journals at once over too.

That also makes me realize that we don't include that full list of journals we started with anywhere. An issue with publishing it as is is that I think there were often multiple possible reasons for excluding a journal but we typically only list one.

**Comment by SKuebbing** [comment]
I can help update the supplemental materials to show the reasons for exclusion. Do we want that? In my revised text I provided (wrong fork, sorry, so maybe didn't come through?) I added in numbers about the reasons for excluding journals from the journal list.

 I'm ambivalent on including these two journals/topics...

**Comment by seananderson** [comment]
I left the numbers commented out because if we include them we should calculate them in R code so they will update if we tweak anything else.

I think on the last group call we decided to include our full table in the supplement. i.e. this https://github.com/seananderson/ecology-trends/blob/master/data/journal-filtering.csv

**Comment by seananderson** [comment]
I've ordered the journal table according to the "taxon specific" category to make it easier to read. At this point I have not included the full table (it would require quite a bit of extra work to make the category labels clean and complete). For now I added this to the caption "Other journals from the ’Ecology and Evolutionary Biology’ and ’Biological Sciences’ JSTOR categories were excluded in an earlier screening phase if they were deemed do not have sufficient temporal coverage, to be region specific, or to be not directly relevant to ecology or conservation biology." (details about that are in the methods)
