### ISSUE TITLE
field + lab experiments in decline

### ISSUE THREAD

**Issue by meredithholgerson** [seananderson/ecology-trends#37]
Should we speculate on why lab and field experiments have declined? This might link to natural history / increase in modeling, etc.? Any published literature we could cite?

**Comment by seananderson** [comment]
Might be a good opportunity to cite Brent's paper (Long-term studies contribute disproportionately to ecology and policy):https://pdfs.semanticscholar.org/ac49/e606dc37536a6030584ac109d1697b622096.pdf

@bbhughes do you want to synthesize a few words on this and can you think of other relevant research on this?

Perhaps combined with:
Osenberg, C. W., Sarnelle, O., Cooper, S. D. & Holt, R. D. Resolving ecological questions through meta-analysis: Goals, metrics, and models. Ecology 80, 1105–1117 (1999).

which we already cite.

**Comment by bbhughes** [comment]
Hi All, chiming in a bit late but I think Meredith makes some good points.
Some have been discussed before, eg the downfall of experiments. For this I
think a lot of it has to do with the 1. The rise of big data, 2. The rise
of meta analyses (why do an expensive low impact experiment when you can
use other people’s experiments to write high impact papers). 3. With
respect to long term monitoring, lots of monitoring programs are starting
to reach decades to multiple decades, and there is a lot of emphasis on
writing up those trends.

I’m moving my folks across country right now (greetings from Sidney, NE) so
I’ll chime in ASAP.

Brent

**Comment by seananderson** [comment]
@bbhughes, feel free to add a sentence somewhere and cite your paper (or if it's easiest just tell me what to add where)
