### ISSUE TITLE
Filter down the top 144 terms by time period

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#38]
These are the current versions:
https://www.dropbox.com/sh/dp26b2w5zt83r6p/AAD3UPkReal_YntKSGnYl_o2a?dl=1

It would be useful if somebody could finish removing terms that we don't think should be included. Debatably we should also be removing all 2-grams that are part of journal titles.

It would probably be easiest if you formatted them like this (which shows my current filtering):

```r
excludes <- c("of", "in", "to", "and", "the", "from",
  "fig", "table", "figure", "vol", "tion")
exclude2 <- c("fig", "use", "doi", "case", "tion", "cent", "while", "results", 
  "table", "figure", "journal", "university", "author", "eve")
exclude3 <- c("american naturalist", "ecological monographs",
  "biol bull", "woods hole", "experi ments",
  "condi tions", "indi viduals", "comp physiol",
  "empty declaremathsizes", "university press",
  "conservation biology", "ecological society",
  "coastal research", "Journal compilation",
  "Blackwell publishing", "british ecological",
  "ecological applications", "cambridge university",
  "authors journal", "canadian journal",
  "royal society", "ecol evol", "state university",
  "springer verlag", "phil trans", "much more", "same time",
  "united states", "other hand", "philosophical transactions",
  "corresponding editor", "ecol monogr", "conserv biol",
  "ecol lett", "popu lations", "ecology letters",
  "research institute", "press chicago", "ecol syst",
  "funct ecol", "change biology", "author contributions",
  "phil wrans", "portugal issn", "nati acad", "proc nati",
  "corresponding author")

exclude <- c("iii", "nat", "min", "bull", "physiol", "zool", "line", "und",
  "note", "trans", "ment", "pre", "dis", "way", "pre", "soc", "other",
  "i.e", "ing", "biol", "might", "ecol", "fontenc", "encodingdefault",
  "American", "part", "well", "following", "paper", "example", "term",
  "show", "press", "series", "fig", "figure")

exclude2 <- c("nature lond", "tempera ture", "popula tion", "tempera tures",
  "cell comp", "raqhi nala", "much high", "limnol oceanogr", "anim ecol",
  "plant physiol", "biochem physiol", "abun dance", "natl acad",
  "progress series", "trend ecol", "blackwell publishing", "annual review",
  "factor such", "national academy", "behav ecol", "academi press",
  "comment ecology", "comp biochem", "address department", "science foundation",
  "geol surv", "press princeton", "john wiley", "signifi cantly", "popu lation",
  "proc natl", "academic press", "research council", "document documentclass",
  "species such", "special issue", "much low", "experi mental", "much great",
  "mcgraw hill", "much low", "other word", "cell biol", "natn acad",
  "proc natn", "oecologia berlin", "observa tion", "short article",
  "biophys acta", "amer natur", "present address", "many other",
  "chicago press", "Chicago press", "relation ship", "blackwell science",
  "research special", "press Cambridge", "press cambridge", "landscape mathrm"
)
```

**Comment by seananderson** [comment]
Also, identify anything interesting in these figures that should be highlighted in the results. If something fits nicely with an existing hand-picked panel then we could add it. 

Off the top of my head: I might add personal communication to the unpublished data/supporting information panel.

**Comment by SKuebbing** [comment]
Sean, same comment is also in the "go through csv files with fine tooth comb", but here too:
NOTES FROM STUDYING DECADEAL Giants

For 1-grams, these terms were top terms in all 4 periods. I’ve added suggested areas to include them…if we want to capture them in the main text:
-	“region”, could add to “scale” panel for community ecology. Maybe too vague?

For  1-grams, these terms popped up as popular in the last period, but not prior

-	“Parameter” add as a term in the Models for inference panel (Methods Figure)?
-	“Probability” add as a term in the Hypothesis testing panel (Methods Figure)?
-	“Variable” add as a term in the Models for inference panel (Methods Figure)?


-	What about a Scientific Methods panel?  Don’t know where it would fit, but some interesting patterns with single terms happending in decadal giants that fit this idea:
o	“Observation” (top 144 for first three periods, NOT in the fourth; linkes to idea that we’re losing natural history and not making observations?)
o	“Hypothesis”: become a top 144 term in the 3rd period (80s) and not commonly used before then.
o	“Experiment”: top 144 term for all four decadal periods
o	“Data”: top 144 term for all four decadal periods; “analysis”: top 144 term for all four decadal periods
o	“conclusion” – never a top term in any period??? 

“USA” becomes a top 1-gram in the last two periods. Does this demonstrate the dominance of publications coming out of the US in ecological literature; or does it mean that JSTOR is biased?

towards US publications (for example, if all the ESA jouranls are in JSTORE but not BES that could create the bias; not that an American can’t publish in BES and vice versa….). Along these same lines, “costa rica” and “puerto rico” come up as regions in the 2-grams in the 60s. sort of interesting? North Carolina is a top term in the 00s? north America is top term throughout. Future paper on WHERE we do ecology in the making….

I suggested above including “personal communication” with the Supporting Information panel of the methods figure. It does come up as a top 2-gram in the 60s-90 decadale panels, with a steep drop in the last period.  Also interesting is “phd thesis” with a very similar trend; we don’t cite theses or personal comm, we just put stuff online to support our arguments.

There are a lot of subdisciplines of ecology that pop up in the 2-grams starting in the 60s – and ecology as a 1-gram has an interesting trajectory.  Might be worth considering a “subfields of ecology” panel?  Also don’t know where this would go…
-	“biological sciences” is top term periods 2-4
-	“biological conservation” becomes a top term in period 4
-	“animal ecology” arises in period 3 (80s)
-	“functional ecology” arises in period 3 (80s)
-	“holarctic ecology” arises in period 3 (80s)
-	“marine biology” arises in period 3 (80s)
-	“population biology” arises in period 3 (80s)
-	“evolutionary biology” arises in period 4 (00s)
-	“global ecology” arises in period 4 (00s)

**Comment by SKuebbing** [comment]
I don't think there are any 1-grams that justify exclusion, beyond what you already have. They are all valid terms. Note that some (like "animal" and "plant") are parts of journal titles, but I think that would be too conservative of a cut.

You'll be aghast to know that I typed out all the one grams across time for thinking about any missing terms to add to our files.  The data is here; I know you could recreate this in a bout 4 seconds....

[Decadal 1grams.xlsx](https://github.com/seananderson/ecology-trends/files/3257853/Decadal.1grams.xlsx)

**Comment by SKuebbing** [comment]
Okay... looking at our list of journals i think that my last point above about subdisciplines is moot; holarctic ecology is a journal title, as is "global ecology"... Ill add these to the "to remove" list

**Comment by SKuebbing** [comment]
Here's some more code for final exclusions of decadal lists. I removed all 2 grams that correspond with 88 journal titles used in the analysis. This doesn't include "marine biology" because we don't have a journal with that name.. you might want to include?

 I wasn't sure if you needed the code separated by decade/period or just all together. I provide both:

Exclude_2gram_1920 <- c(“approxi mately”, “biol chem”, “chromo somes”, “experi ment”)
Exclude_2gram_1960 <- c(“approxi mately”, “biol chem”, “biological science”, “physiol lond” )
Exclude_2gram_1980 <- c(“animal ecology”, “biological science”, “functional ecology”, “holarctic ecology”, “press london” )
Exclude_2gram_2000 <- c(“animal ecology”, “biological conservation”, “functional ecology”, “global change”, “global ecology”, “press london” )

ExcludeAll <- c((“animal ecology”, “approxi mately”, “biol chem”, “biological conservation”, “biological science”, “chromo somes”, “experi ment”, “functional ecology”, “global change”, “global ecology”, “holarctic ecology”,  “physiol lond”,  “press london”)



There was one other odd terms that seems funny, but I’d like other’s opinions:

“ecology progress” only in the 2000-2010 list

**Comment by seananderson** [comment]
Thanks @SKuebbing, I've added these and when I rerun the code the figures will get updated. 'ecology progress' is probably from the journal "marine ecology progress series".
