### ISSUE TITLE
Extract data for possible zombie terms

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#6]
intermediate disturbance hypothesis
optimal foraging
climax community
fishing down the
down the food
intermediate disturbance
optimal foraging theory
k selection
r selection
r/k
r k
humped diversity productivity

(check hyphens and slashes)

**Comment by bbhughes** [comment]
Yes, I think they are all there for this first round. Brent will share the master list with zombie group to identify any other zombie terms. Also casually ask colleagues.

**Comment by seananderson** [comment]
Extracted here https://github.com/seananderson/ecology-trends/blob/39699cd9f8abe2648f3ba939221b0c8aee15c64e/data/generated/zombie-request1.rds

With the code: https://github.com/seananderson/ecology-trends/blob/39699cd9f8abe2648f3ba939221b0c8aee15c64e/analysis/5-extract-gram-data.R#L121-L126
